[32m2024-03-23 21:17:46 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 66496b2a-9efa-41ab-b586-66bc167fa5ba - 1236053 - LOGS_CAPTURED - Started capturing logs in process (pid: 1236053).
[32m2024-03-23 21:17:46 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 66496b2a-9efa-41ab-b586-66bc167fa5ba - 1236053 - player_stats - STEP_START - Started execution of step "player_stats".
[32m2024-03-23 21:17:52 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 66496b2a-9efa-41ab-b586-66bc167fa5ba - 1236053 - player_stats - STEP_OUTPUT - Yielded output "result" of type "DataFrame". (Type check passed).
[32m2024-03-23 21:17:57 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 66496b2a-9efa-41ab-b586-66bc167fa5ba - 1236053 - player_stats - STEP_FAILURE - Execution of step "player_stats" failed.

dagster._core.errors.DagsterExecutionHandleOutputError: Error occurred while handling output "result" of step "player_stats"::

google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/dezoomcamp-411023/jobs?uploadType=multipart: Provided Schema does not match Table dezoomcamp-411023:nba_data.player_stats. Cannot add fields (field: TS%_VALUE)

Stack Trace:
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 463, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 797, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/dagster/_core/storage/db_io_manager.py", line 147, in handle_output
    handler_metadata = self._handlers_by_type[obj_type].handle_output(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/dagster_gcp_pandas/bigquery/bigquery_pandas_type_handler.py", line 49, in handle_output
    job = connection.load_table_from_dataframe(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py", line 2749, in load_table_from_dataframe
    return self.load_table_from_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py", line 2513, in load_table_from_file
    raise exceptions.from_http_response(exc.response)

The above exception occurred during handling of the following exception:
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)

Stack Trace:
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py", line 2509, in load_table_from_file
    response = self._do_multipart_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py", line 3073, in _do_multipart_upload
    response = upload.transmit(
               ^^^^^^^^^^^^^^^^
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/google/resumable_media/requests/upload.py", line 149, in retriable_request
    self._process_response(result)
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/google/resumable_media/_upload.py", line 125, in _process_response
    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)
  File "/home/gbemike/Documents/github/nba_pipeline/.venv/lib/python3.11/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
[0m
